/* These is for the coordinates for the HBTC.  Go under Map.dm and change EnterHBTC and ExitHBTC
Entrance goes to (227,258,16) Exit goes to (216,86,11)
			*/
//mob/var/Grabbable

turf
	Health=90001000
//	Inside=0

	Terrain/Tiles
		icon='NewTurfs.dmi'
		Icon1
			icon_state="1"
		Icon2
			icon_state="2"
		Icon3
			icon_state="3"
		Icon4
			icon_state="4"
		Icon5
			icon_state="5"
		Icon6
			icon_state="6"
		Icon7
			icon_state="7"
		Icon8
			icon_state="8"
			density=1
		Icon9
			icon_state="9"
		Icon10
			icon_state="10"
		Icon11
			icon_state="11"
		Icon12
			icon_state="12"
		Icon13
			icon_state="13"
		Icon14
			icon_state="14"
		Icon15
			icon_state="15"
		Icon16
			icon_state="16"
		Icon17
			icon_state="17"
		Icon18
			icon_state="18"
		Icon19
			icon_state="19"
		Icon20
			icon_state="20"
		Icon21
			icon_state="21"
		Icon22
			icon_state="22"
		Icon23
			icon_state="23"
		Icon24
			icon_state="24"
		Icon25
			icon_state="25"
		Icon26
			icon_state="26"
		Icon27
			icon_state="27"
		Icon28
			icon_state="28"
		Icon29
			icon_state="29"
		Icon30
			icon_state="30"
		Icon31
			icon_state="31"
		Icon32
			icon_state="32"
		Icon33
			icon_state="33"
		Icon34
			icon_state="34"
		Icon35
			icon_state="35"
		Icon36
			icon_state="36"
		Icon37
			icon_state="37"
		Icon38
			icon_state="38"
		Icon39
			icon_state="39"
		Icon40
			icon_state="40"
		Icon41
			icon_state="41"
		Icon42
			icon_state="42"
		Icon43
			icon_state="43"
		Icon44
			icon_state="44"
		Icon45
			icon_state="45"
		Icon46
			icon_state="46"
		Icon47
			icon_state="47"
		Icon48
			icon_state="48"
		Icon49
			icon_state="49"
		Icon50
			icon_state="50"
		Icon51
			icon_state="51"
		Icon52
			icon_state="52"
		Icon53
			icon_state="53"
		Icon54
			icon_state="54"
		Icon55
			icon_state="55"
		Icon56
			icon_state="56"
			density=1
		Icon57
			icon_state="57"
		Icon58
			icon_state="58"
		Icon60
			icon_state="60"
		Icon61
			icon_state="61"
		Icon62
			icon_state="62"
		Icon63
			icon_state="63"
		Icon64
			icon_state="64"
		Icon65
			icon_state="65"
		Icon66
			icon_state="66"
		Icon67
			icon_state="67"

//Dirt turfs
	Terrain/Ground
		Dirt1
			icon='Dirt.dmi'
			icon_state="Dirt1"
		Dirt2
			icon='Dirt.dmi'
			icon_state="Dirt2"
		Dirt3
			icon='Dirt.dmi'
			icon_state="Dirt3"
		Dirt4
			icon='Dirt.dmi'
			icon_state="Dirt4"
		Dirt4R
			icon='Dirt.dmi'
			icon_state="Dirt4Rock"
			density=1
		Dirt4C
			icon='Dirt.dmi'
			icon_state="Dirt4Crack"
		Dirt5
			icon='Dirt.dmi'
			icon_state="Dirt5"
		Dirt6
			icon='Dirt.dmi'
			icon_state="Dirt6"
		Dirt7
			icon='Dirt.dmi'
			icon_state="Dirt7"
		Dirt8
			icon='Dirt.dmi'
			icon_state="Dirt8"
		Dirt9
			icon='Dirt.dmi'
			icon_state="Dirt9"
		Dirt10
			icon='Dirt.dmi'
			icon_state="Dirt10"
		Dirt11
			icon='Dirt.dmi'
			icon_state="Dirt11"
		Dirt12
			icon='Dirt.dmi'
			icon_state="Dirt12"
		Dirt13
			icon='Dirt.dmi'
			icon_state="Dirt13"
		Dirt14
			icon='Dirt.dmi'
			icon_state="Dirt14"
//Sand turfs

		Sand1
			icon='BigSandTurf.dmi'
			/*New()
				..()
				if(prob(50)) icon_state="[rand(0,3)],[rand(0,3)]"*/
		OldSand1
			icon='Dirt.dmi'
			icon_state="Sand1"
		Sand2
			icon='Dirt.dmi'
			icon_state="Sand2"
		Sand3
			icon='Dirt.dmi'
			icon_state="Sand3"
		Sand4
			icon='Dirt.dmi'
			icon_state="Sand4"
		Sand5
			icon='Dirt.dmi'
			icon_state="Sand5"
		Sand6
			icon='Dirt.dmi'
			icon_state="Sand6"
		Sand7
			icon='Dirt.dmi'
			icon_state="Sand7"
		Sand8
			icon='Dirt.dmi'
			icon_state="Sand8"
		Sand9
			icon='Dirt.dmi'
			icon_state="Sand9"
		Sand10
			icon='Dirt.dmi'
			icon_state="Sand10"
		Sand11
			icon='Dirt.dmi'
			icon_state="Sand11"
		Sand12
			icon='Dirt.dmi'
			icon_state="Sand12"
		Sand13
			icon='Dirt.dmi'
			icon_state="Sand13"
		Sand14
			icon='Dirt.dmi'
			icon_state="Sand14"
		Sand15
			icon='Dirt.dmi'
			icon_state="Sand15"
		Sand16
			icon='Dirt.dmi'
			icon_state="Sand16"
		Sand17
			icon='Dirt.dmi'
			icon_state="Sand17"
		Sand18
			icon='Dirt.dmi'
			icon_state="Sand18"
		Sand19
			icon='Dirt.dmi'
			icon_state="Sand19"
		Ice1
			icon='Natural.dmi'
			icon_state="Ice1"
		Ice2
			icon='BigIceTurf3.dmi'
			/*New()
				..()
				if(prob(50)) icon_state="[rand(0,5)],[rand(0,5)]"*/
		OldIce2
			icon='Natural.dmi'
			icon_state="Ice2"
		Ice3
			icon='Natural.dmi'
			icon_state="Ice3"
		Stone1
			icon='Natural.dmi'
			icon_state="Stone1"
		Stone2
			icon='Natural.dmi'
			icon_state="Stone2"
		Stone3
			icon='Natural.dmi'
			icon_state="Stone3"
		Stone4
			icon='Natural.dmi'
			icon_state="Stone4"
		Stone5
			icon='Natural.dmi'
			icon_state="Stone5"
		Stone6
			icon='Natural.dmi'
			icon_state="Stone6"
		Stone7
			icon='Natural.dmi'
			icon_state="Stone7"
		Stone8
			icon='Natural.dmi'
			icon_state="Stone8"
		Stone9
			icon='Natural.dmi'
			icon_state="Stone9"
		Stone10
			icon='Natural.dmi'
			icon_state="Stone10"
		Stone11
			icon='Natural.dmi'
			icon_state="Stone11"
		Stone12
			icon='Natural.dmi'
			icon_state="Stone12"
		Stone13
			icon='Natural.dmi'
			icon_state="Stone13"
		Stone14
			icon='Natural.dmi'
			icon_state="Stone14"
		Stone15
			icon='Natural.dmi'
			icon_state="Stone15"
		Stone16
			icon='Natural.dmi'
			icon_state="Stone16"
		Stone17
			icon='Natural.dmi'
			icon_state="Stone17"
		Misc1
			icon='Misc2.dmi'
			icon_state="Misc1"
		Misc2
			icon='Misc2.dmi'
			icon_state="Misc2"
		Misc3
			icon='Misc2.dmi'
			icon_state="Misc3"
		Misc4
			icon='Misc2.dmi'
			icon_state="Misc4"
		Misc5
			icon='Misc2.dmi'
			icon_state="Misc5"
		Misc6
			icon='Misc2.dmi'
			icon_state="Misc6"
		Misc7
			icon='Misc2.dmi'
			icon_state="Misc7"
		Misc8
			icon='Misc2.dmi'
			icon_state="Misc8"
		Misc9
			icon='Misc2.dmi'
			icon_state="Misc9"
		Misc10
			icon='Misc2.dmi'
			icon_state="Misc10"
		Misc11
			icon='Misc2.dmi'
			icon_state="Misc11"
		Misc12
			icon='Misc2.dmi'
			icon_state="Misc12"
		Misc13
			icon='Misc2.dmi'
			icon_state="Misc13"
		Misc14
			icon='Misc2.dmi'
			icon_state="Misc14"
		Misc15
			icon='Misc2.dmi'
			icon_state="Misc15"
		Misc16
			icon='Misc2.dmi'
			icon_state="Misc16"
		Misc17
			icon='Misc2.dmi'
			icon_state="Misc15"
		Misc18
			icon='Misc2.dmi'
			icon_state="Misc16"

//Grass turfs
	Terrain/Grass
		Grass1
			icon='BigGrass.dmi'
			/*New()
				..()
				if(prob(50)) icon_state="[rand(0,3)],[rand(0,3)]"*/
		OldGrass1
			icon='Grass.dmi'
			icon_state="Grass1"
		Grass2
			icon='Grass.dmi'
			icon_state="Grass2"
		Grass3
			icon='Grass.dmi'
			icon_state="Grass3"
		Grass4
			icon='Grass.dmi'
			icon_state="Grass4"
		Grass5
			icon='Grass.dmi'
			icon_state="Grass5"
		Grass6
			icon='Grass.dmi'
			icon_state="Grass6"
		Grass7
			icon='BigGrassTurf2.dmi'
			/*New()
				..()
				if(prob(50)) icon_state="[rand(0,2)],[rand(0,2)]"*/
		OldGrass7
			icon='Grass.dmi'
			icon_state="Grass7"
		Grass8
			icon='Grass.dmi'
			icon_state="Grass8"
		Grass9
			icon='Grass.dmi'
			icon_state="Grass9"
		Grass10
			icon='Grass.dmi'
			icon_state="Grass10"
		Grass11
			icon='Grass.dmi'
			icon_state="Grass11"
		Grass12
			icon='Grass.dmi'
			icon_state="Grass12"
		Grass13
			icon='Grass.dmi'
			icon_state="Grass13"
		Grass14
			icon='Grass.dmi'
			icon_state="Grass14"
		Grass15
			icon='Grass.dmi'
			icon_state="Grass15"
		Grass16
			icon='BigGrassandDirtTurf.dmi'
			/*New()
				..()
				if(prob(50)) icon_state="[rand(0,2)],[rand(0,2)]"*/
		OldGrass16
			icon='Grass.dmi'
			icon_state="Grass16"
		Grass17
			icon='Grass.dmi'
			icon_state="Grass17"
		Grass18
			icon='Grass.dmi'
			icon_state="Grass18"
		Grass19
			icon='BigSnowTurf.dmi'
			/*New()
				..()
				if(prob(50)) icon_state="[rand(0,5)],[rand(0,5)]"*/
		OldGrass19
			icon='Grass.dmi'
			icon_state="Grass19"
		Grass20
			icon='Grass.dmi'
			icon_state="Grass20"
		Grass21
			icon='Grass.dmi'
			icon_state="Grass21"
		Grass22
			icon='Grass.dmi'
			icon_state="Grass22"
		Grass23
			icon='Grass.dmi'
			icon_state="Grass23"
		Grass24
			icon='Grass.dmi'
			icon_state="Grass24"
//Natural turfs
	Terrain/Tiles
		Wood1
			icon='Natural.dmi'
			icon_state="Wood1"
		Wood2
			icon='Natural.dmi'
			icon_state="Wood2"
		Wood3
			icon='Natural.dmi'
			icon_state="Wood3"
		Wood4
			icon='Natural.dmi'
			icon_state="Wood4"
		Wood5
			icon='Natural.dmi'
			icon_state="Wood5"
		Wood6
			icon='Natural.dmi'
			icon_state="Wood6"
		Wood7
			icon='Natural.dmi'
			icon_state="Wood7"
		Wood8
			icon='Natural.dmi'
			icon_state="Wood8"
		Wood9
			icon='Natural.dmi'
			icon_state="Wood9"
		Wood10
			icon='Natural.dmi'
			icon_state="Wood10"
		Wood11
			icon='Natural.dmi'
			icon_state="Wood11"
		Wood12
			icon='Natural.dmi'
			icon_state="Wood12"
		Wood13
			icon='Natural.dmi'
			icon_state="Wood13"
		Wood14
			icon='Natural.dmi'
			icon_state="Wood14"
		Wood15
			icon='Natural.dmi'
			icon_state="Wood15"
		Wood16
			icon='Natural.dmi'
			icon_state="Wood16"
		Wood17
			icon='Natural.dmi'
			icon_state="Wood17"
	//Technology turfs
		Tech1
			icon='Technology.dmi'
			icon_state="Tech1"
		Tech2
			icon='Technology.dmi'
			icon_state="Tech2"
		Tech3
			icon='Technology.dmi'
			icon_state="Tech3"
		Tech4
			icon='Technology.dmi'
			icon_state="Tech4"
		Tech5
			icon='Technology.dmi'
			icon_state="Tech5"
		Tech5B
			icon='Technology.dmi'
			icon_state="Tech5B"
		Tech6
			icon='Technology.dmi'
			icon_state="Tech6"
		Tech7
			icon='Technology.dmi'
			icon_state="Tech7"
		Tech8
			icon='Technology.dmi'
			icon_state="Tech8"
		Tech9
			icon='Technology.dmi'
			icon_state="Tech9"
		Tech10
			icon='Technology.dmi'
			icon_state="Tech10"
		Tech11
			icon='Technology.dmi'
			icon_state="Tech11"
		Tech12
			icon='Technology.dmi'
			icon_state="Tech12"
		Tech13
			icon='Technology.dmi'
			icon_state="Tech13"
		Tech14
			icon='Technology.dmi'
			icon_state="Tech14"
		Tech15
			icon='Technology.dmi'
			icon_state="Tech15"
		Tech16
			icon='Technology.dmi'
			icon_state="Tech16"
		Tech17
			icon='Technology.dmi'
			icon_state="Tech17"
	//Tiles and Carpets turfs
		Tile1
			icon='Tiles.dmi'
			icon_state="Tile1"
		Tile2
			icon='Tiles.dmi'
			icon_state="Tile2"
		Tile3
			icon='Tiles.dmi'
			icon_state="Tile3"
		Tile4
			icon='Tiles.dmi'
			icon_state="Tile4"
		Tile5
			icon='Tiles.dmi'
			icon_state="Tile5"
		Tile6
			icon='Tiles.dmi'
			icon_state="Tile6"
		Tile7
			icon='Tiles.dmi'
			icon_state="Tile7"
		Tile8
			icon='Tiles.dmi'
			icon_state="Tile8"
		Tile9
			icon='Tiles.dmi'
			icon_state="Tile9"
		Tile10
			icon='Tiles.dmi'
			icon_state="Tile10"
		Tile11
			icon='Tiles.dmi'
			icon_state="Tile11"
		Tile12
			icon='Tiles.dmi'
			icon_state="Tile12"
		Tile13
			icon='Tiles.dmi'
			icon_state="Tile13"
		Tile14
			icon='Tiles.dmi'
			icon_state="Tile14"
		Tile15
			icon='Tiles.dmi'
			icon_state="Tile15"
		Tile16
			icon='Tiles.dmi'
			icon_state="Tile16"
		Tile17
			icon='Tiles.dmi'
			icon_state="Tile17"
		Tile18
			icon='Tiles.dmi'
			icon_state="Tile18"
		Tile19
			icon='Tiles.dmi'
			icon_state="Tile19"
		Tile20
			icon='Tiles.dmi'
			icon_state="Tile20"
		Tile21
			icon='Tiles.dmi'
			icon_state="Tile21"
		Tile22
			icon='Tiles.dmi'
			icon_state="Tile22"
		Tile23
			icon='Tiles.dmi'
			icon_state="Tile23"
		Tile24
			icon='Tiles.dmi'
			icon_state="Tile24"
		Tile25
			icon='Tiles.dmi'
			icon_state="Tile25"
		Tile26
			icon='Tiles.dmi'
			icon_state="Tile26"
		Tile27
			icon='Tiles.dmi'
			icon_state="Tile27"
		Tile28
			icon='Tiles.dmi'
			icon_state="Tile28"
		Tile29
			icon='Tiles.dmi'
			icon_state="Tile29"
		Tile30
			icon='Tiles.dmi'
			icon_state="Tile30"
		Tile31
			icon='Tiles.dmi'
			icon_state="Tile31"
		Tile32
			icon='Tiles.dmi'
			icon_state="Tile32"
		Tile33
			icon='Tiles.dmi'
			icon_state="Tile33"
		Tile34
			icon='Tiles.dmi'
			icon_state="Tile34"
		Tile35
			icon='Tiles.dmi'
			icon_state="Tile35"
		Tile36
			icon='Tiles.dmi'
			icon_state="Tile36"
		Tile37
			icon='Tiles.dmi'
			icon_state="Tile37"
		Tile38
			icon='Tiles.dmi'
			icon_state="Tile38"
		Tile39
			icon='Tiles.dmi'
			icon_state="Tile39"
		Tile40
			icon='Tiles.dmi'
			icon_state="Tile40"
		Tile41
			icon='Tiles.dmi'
			icon_state="Tile41"
		Tile42
			icon='Tiles.dmi'
			icon_state="Tile42"
		Tile43
			icon='Tiles.dmi'
			icon_state="Tile43"
		Tile44
			icon='Tiles.dmi'
			icon_state="Tile44"
		Carpet1
			icon='Tiles.dmi'
			icon_state="Carpet1"
		Carpet2
			icon='Tiles.dmi'
			icon_state="Carpet2"
		Carpet3
			icon='Tiles.dmi'
			icon_state="Carpet3"
		Carpet4
			icon='Tiles.dmi'
			icon_state="Carpet4"
		Carpet5
			icon='Tiles.dmi'
			icon_state="Carpet5"
		Carpet6
			icon='Tiles.dmi'
			icon_state="Carpet6"
		Carpet7
			icon='Tiles.dmi'
			icon_state="Carpet7"
		Carpet8
			icon='Tiles.dmi'
			icon_state="Carpet8"
//Misc turfs

//Wall turfs

	Upgradeable/Walls
		Wall1
			icon='Walls.dmi'
			icon_state="Wall1"
			density=1
		Wall2
			icon='Walls.dmi'
			icon_state="Wall2"
			density=1
		Wall3
			icon='Walls.dmi'
			icon_state="Wall3"
			density=1
		Wall4
			icon='Walls.dmi'
			icon_state="Wall4"
			density=1
		Wall5
			icon='Walls.dmi'
			icon_state="Wall5"
			density=1
		Wall6
			//Health=10000000000
			icon='Walls.dmi'
			icon_state="Wall6"
			density=1
		Wall6R
			icon='Walls.dmi'
			icon_state="Wall6R"
			density=1
		Wall6G
			icon='Walls.dmi'
			icon_state="Wall6G"
			density=1
		Wall6B
			icon='Walls.dmi'
			icon_state="Wall6B"
			density=1
		Wall6Y
			icon='Walls.dmi'
			icon_state="Wall6Y"
			density=1
		Wall6W
			icon='Walls.dmi'
			icon_state="Wall6W"
			density=1
		Wall7
			//Health=100000000000000
			icon='Walls.dmi'
			icon_state="Wall7"
			density=1
		Wall8
			icon='Walls.dmi'
			icon_state="Wall8"
			density=1
		Wall9
			icon='Walls.dmi'
			icon_state="Wall9"
			density=1
		Wall10
			icon='Walls.dmi'
			icon_state="Wall10"
			density=1
		Wall11
			icon='Walls.dmi'
			icon_state="Wall11"
			density=1
		Wall12
			icon='Walls.dmi'
			icon_state="Wall12"
			density=1
		Wall13
			icon='Walls.dmi'
			icon_state="Wall13"
			density=1
		Wall14
			icon='Walls.dmi'
			icon_state="Wall14"
			density=1
		Wall15
			icon='Walls.dmi'
			icon_state="Wall15"
			density=1
		Wall16
			icon='Walls.dmi'
			icon_state="Wall16"
			density=1
		Wall17
			icon='Walls.dmi'
			icon_state="Wall17"
			density=1
		Wall18
			icon='Walls.dmi'
			icon_state="Wall18"
			density=1
		Wall19
			icon='Walls.dmi'
			icon_state="Wall19"
			density=1
		Wall20
			icon='Walls.dmi'
			icon_state="Wall20"
			density=1
		Wall21
			icon='Walls.dmi'
			icon_state="Wall21"
			density=1
		Wall22
			icon='Walls.dmi'
			icon_state="Wall22"
			density=1
		Wall23
			icon='Walls.dmi'
			icon_state="Wall23"
			density=1
		Wall24
			icon='Walls.dmi'
			icon_state="Wall24"
			density=1
		Wall25
			icon='Walls.dmi'
			icon_state="Wall25"
			density=1
		Wall26
			icon='Walls.dmi'
			icon_state="Wall26"
			density=1
		Wall27
			icon='Walls.dmi'
			icon_state="Wall27"
			density=1
		Wall28
			icon='Walls.dmi'
			icon_state="Wall28"
			density=1
		Wall29
			icon='Walls.dmi'
			icon_state="Wall29"
			density=1
		Wall30
			icon='Walls.dmi'
			icon_state="Wall30"
			density=1
		Wall31
			//Health=100000000000000
			icon='Walls.dmi'
			icon_state="Wall31"
			density=1
		Wall32
			icon='Walls.dmi'
			icon_state="Wall32"
			density=1
		Wall33
			icon='Walls.dmi'
			icon_state="Wall33"
			density=1
		Wall34
			icon='Walls.dmi'
			icon_state="Wall34"
			density=1
		Wall35
			icon='Walls.dmi'
			icon_state="Wall35"
			density=1
		Wall36
			icon='Walls.dmi'
			icon_state="Wall36"
			density=1
		Wall37
			icon='Walls.dmi'
			icon_state="Wall37"
			density=1
		Wall38
			icon='Walls.dmi'
			//Health=100000000000000
			icon_state="Wall38"
			density=1
		Wall39
			icon='Walls.dmi'
			icon_state="Wall39"
			density=1
		Wall40
			icon='Walls.dmi'
			icon_state="Wall40"
			density=1
		Wall41
			icon='Walls.dmi'
			icon_state="Wall41"
			density=1
		Wall42
			icon='Walls.dmi'
			icon_state="Wall42"
			density=1
		Wall43
			icon='Walls.dmi'
			icon_state="Wall43"
			density=1
		Wall44
			icon='Walls.dmi'
			icon_state="Wall44"
			density=1
		Wall45
			icon='Walls.dmi'
			icon_state="Wall45"
			density=1
		Wall46
			icon='Walls.dmi'
			icon_state="Wall46"
			density=1
		Wall47
			icon='Walls.dmi'
			icon_state="Wall47"
			density=1
		Wall48
			icon='Walls.dmi'
			icon_state="Wall48"
			density=1
		Wall49
			icon='Walls.dmi'
			icon_state="Wall49"
			density=1
		Wall50
			icon='Walls.dmi'
			icon_state="Wall50"
			density=1
		Wall51
			icon='Walls.dmi'
			icon_state="Wall51"
			density=1
		Wall52
			icon='Walls.dmi'
			icon_state="Wall52"
			density=1
		Wall53
			icon='Walls.dmi'
			icon_state="Wall53"
			density=1
		Wall54
			icon='Walls.dmi'
			icon_state="Wall54"
			density=1
		Wall55
			icon='Walls.dmi'
			icon_state="Wall55"
			density=1
		Wall56
			icon='Walls.dmi'
			icon_state="Wall56"
			density=1
		Wall57
			icon='Walls.dmi'
			icon_state="Wall57"
			density=1


//Roof turfs
turf
	Upgradeable/Roofs
//		FlyOverAble=0
		Enter(atom/A)
			if(FlyOverAble||ghostDens_check(A)) return ..()
			else return
		Roof1
			icon='Roofs.dmi'
			icon_state="Roof1"
			density=1
			opacity=1
			Enter(atom/A)
				if(FlyOverAble||ghostDens_check(A)) return ..()
				else return
		Roof1C
			icon='Roofs.dmi'
			icon_state="Roof1C"
			density=1
			opacity=1
			//FlyOverAble=0
			Enter(atom/A)
				if(FlyOverAble||ghostDens_check(A)) return ..()
				else return
		Roof2
			icon='Roofs.dmi'
			icon_state="Roof2"
			density=1
			opacity=1
			Enter(atom/A)
				if(FlyOverAble||ghostDens_check(A)) return ..()
				else return
		Roof3
			icon='Roofs.dmi'
			icon_state="Roof3"
			density=1
			opacity=1
			//FlyOverAble=0
			Enter(atom/A)
				if(FlyOverAble||ghostDens_check(A)) return ..()
				else return
		Roof4
			icon='Roofs.dmi'
			icon_state="Roof4"
			density=1
			opacity=1
			Enter(atom/A)
				if(FlyOverAble||ghostDens_check(A)) return ..()
				else return
		Roof4C
			icon='Roofs.dmi'
			icon_state="Roof4C"
			density=1
			opacity=1
			Enter(atom/A)
				if(FlyOverAble||ghostDens_check(A)) return ..()
				else return
		Roof5
			icon='Roofs.dmi'
			icon_state="Roof5"
			density=1
			opacity=1
			Enter(atom/A)
				if(FlyOverAble||ghostDens_check(A)) return ..()
				else return
		Roof5C
			icon='Roofs.dmi'
			icon_state="Roof5C"
			density=1
			opacity=1
			Enter(atom/A)
				if(FlyOverAble||ghostDens_check(A)) return ..()
				else return
		Roof6
			icon='Roofs.dmi'
			icon_state="Roof6"
			density=1
			opacity=1
			Enter(atom/A)
				if(FlyOverAble||ghostDens_check(A)) return ..()
				else return
		Roof7
			icon='Roofs.dmi'
			icon_state="Roof7"
			density=1
			//FlyOverAble=0
			opacity=1
			Enter(atom/A)
				if(FlyOverAble||ghostDens_check(A)) return ..()
				else return
		Roof8
			icon='Roofs.dmi'
			icon_state="Roof8"
			density=1
			//FlyOverAble=0
			opacity=1
			Enter(atom/A)
				if(FlyOverAble||ghostDens_check(A)) return ..()
				else return
		Roof9
			icon='Roofs.dmi'
			icon_state="Roof9"
			density=1
			opacity=1
			Enter(atom/A)
				if(FlyOverAble||ghostDens_check(A)) return ..()
				else return
		Roof10
			icon='Roofs.dmi'
			icon_state="Roof10"
			density=1
			opacity=1
			Enter(atom/A)
				if(FlyOverAble||ghostDens_check(A)) return ..()
				else return
		Roof11
			icon='Roofs.dmi'
			icon_state="Roof11"
			//FlyOverAble=0
			density=1
			opacity=1
			Enter(atom/A)
				if(FlyOverAble||ghostDens_check(A)) return ..()
				else return
		Roof12
			icon='Roofs.dmi'
			icon_state="Roof12"
			density=1
			opacity=1
			Enter(atom/A)
				if(FlyOverAble||ghostDens_check(A)) return ..()
				else return
		Roof13
			icon='Roofs.dmi'
			icon_state="Roof13"
			density=1
			opacity=1
			Enter(atom/A)
				if(FlyOverAble||ghostDens_check(A)) return ..()
				else return
		Roof14
			icon='Roofs.dmi'
			icon_state="Roof14"
			density=1
			opacity=1
			Enter(atom/A)
				if(FlyOverAble||ghostDens_check(A)) return ..()
				else return
		Roof15
			icon='Roofs.dmi'
			icon_state="Roof15"
			density=1
			opacity=1
			Enter(atom/A)
				if(FlyOverAble||ghostDens_check(A)) return ..()
				else return
		Roof16
			icon='Roofs.dmi'
			icon_state="Roof16"
			density=1
			opacity=1
			Enter(atom/A)
				if(FlyOverAble||ghostDens_check(A)) return ..()
				else return
		Roof17
			icon='Roofs.dmi'
			icon_state="Roof17"
			density=1
			opacity=1
			Enter(atom/A)
				if(FlyOverAble||ghostDens_check(A)) return ..()
				else return
		Roof18
			icon='Roofs.dmi'
			icon_state="Roof18"
			density=1
			opacity=1
			Enter(atom/A)
				if(FlyOverAble||ghostDens_check(A)) return ..()
				else return
		Roof19
			icon='Roofs.dmi'
			icon_state="Roof19"
			density=1
			opacity=1
			Enter(atom/A)
				if(FlyOverAble||ghostDens_check(A)) return ..()
				else return
		Roof20
			icon='Roofs.dmi'
			icon_state="Roof20"
			//FlyOverAble=0
			density=1
			opacity=1
			Enter(atom/A)
				if(FlyOverAble||ghostDens_check(A)) return ..()
				else return
		Roof21
			icon='Roofs.dmi'
			icon_state="Roof21"
			density=1
			opacity=1
			Enter(atom/A)
				if(FlyOverAble||ghostDens_check(A)) return ..()
				else return
		Roof22
			icon='Roofs.dmi'
			icon_state="Roof22"
			//FlyOverAble=0
			density=1
			opacity=1
			Enter(atom/A)
				if(FlyOverAble||ghostDens_check(A)) return ..()
				else return
	Lookout_Pole
		icon='Korin1.dmi'



turf/Edges
	Grass16NW
		icon='Grass.dmi'
		icon_state="Grass16NW"
	Grass16NE
		icon='Grass.dmi'
		icon_state="Grass16NE"
	Grass16SW
		icon='Grass.dmi'
		icon_state="Grass16SW"
	Grass16SE
		icon='Grass.dmi'
		icon_state="Grass16SE"
	Sand3NW
		icon='Dirt.dmi'
		icon_state="Sand3NW"
	Sand3NE
		icon='Dirt.dmi'
		icon_state="Sand3NE"
	Sand3SW
		icon='Dirt.dmi'
		icon_state="Sand3SW"
	Sand3SE
		icon='Dirt.dmi'
		icon_state="Sand3SE"
	Grass24NW
		icon='Grass.dmi'
		icon_state="Grass24NW"
	Grass24NE
		icon='Grass.dmi'
		icon_state="Grass24NE"
	Grass24SW
		icon='Grass.dmi'
		icon_state="Grass24SW"
	Grass24SE
		icon='Grass.dmi'
		icon_state="Grass24SE"
	Grass23NW
		icon='Grass.dmi'
		icon_state="Grass23NW"
	Grass23NE
		icon='Grass.dmi'
		icon_state="Grass23NE"
	Grass23SW
		icon='Grass.dmi'
		icon_state="Grass23SW"
	Grass23SE
		icon='Grass.dmi'
		icon_state="Grass23SE"
	Grass23EdgeN
		icon='Grass.dmi'
		icon_state="Grass23EdgeN"
	Grass23EdgeS
		icon='Grass.dmi'
		icon_state="Grass23EdgeS"
	Grass23EdgeE
		icon='Grass.dmi'
		icon_state="Grass23EdgeE"
	Grass23EdgeW
		icon='Grass.dmi'
		icon_state="Grass23EdgeW"
	Sand3EdgeN
		icon='Dirt.dmi'
		icon_state="Sand3EdgeN"
	Sand3EdgeS
		icon='Dirt.dmi'
		icon_state="Sand3EdgeS"
	Sand3EdgeE
		icon='Dirt.dmi'
		icon_state="Sand3EdgeE"
	Sand3EdgeW
		icon='Dirt.dmi'
		icon_state="Sand3EdgeW"
	Grass7NW
		icon='Grass.dmi'
		icon_state="Grass7NW"
	Grass7NE
		icon='Grass.dmi'
		icon_state="Grass7NE"
	Grass7SW
		icon='Grass.dmi'
		icon_state="Grass7SW"
	Grass7SE
		icon='Grass.dmi'
		icon_state="Grass7SE"
	Grass7EdgeN
		icon='Grass.dmi'
		icon_state="Grass7EdgeN"
	Grass7EdgeS
		icon='Grass.dmi'
		icon_state="Grass7EdgeS"
	Grass7EdgeE
		icon='Grass.dmi'
		icon_state="Grass7EdgeE"
	Grass7EdgeW
		icon='Grass.dmi'
		icon_state="Grass7EdgeW"
	Dirt3NW
		icon='Dirt.dmi'
		icon_state="Dirt3NW"
	Dirt3NE
		icon='Dirt.dmi'
		icon_state="Dirt3NE"
	Dirt3SW
		icon='Dirt.dmi'
		icon_state="Dirt3SW"
	Dirt3SE
		icon='Dirt.dmi'
		icon_state="Dirt3SE"
	Sand19NW
		icon='Dirt.dmi'
		icon_state="Sand19NW"
	Sand19NE
		icon='Dirt.dmi'
		icon_state="Sand19NE"
	Sand19SW
		icon='Dirt.dmi'
		icon_state="Sand19SW"
	Sand19SE
		icon='Dirt.dmi'
		icon_state="Sand19SE"
	Sand19EdgeN
		icon='Dirt.dmi'
		icon_state="Sand19EdgeN"
	Sand19EdgeS
		icon='Dirt.dmi'
		icon_state="Sand19EdgeS"
	Sand19EdgeE
		icon='Dirt.dmi'
		icon_state="Sand19EdgeE"
	Sand19EdgeW
		icon='Dirt.dmi'
		icon_state="Sand19EdgeW"
	Grass16EdgeN
		icon='Grass.dmi'
		icon_state="Grass16EdgeN"
	Grass16EdgeS
		icon='Grass.dmi'
		icon_state="Grass16EdgeS"
	Grass16EdgeE
		icon='Grass.dmi'
		icon_state="Grass16EdgeE"
	Grass16EdgeW
		icon='Grass.dmi'
		icon_state="Grass16EdgeW"


obj/Turfs

	CustomObj1
		icon='ArtificalObj.dmi'
		icon_state="QuestionMark"

	Glass
		Urban_Glass_Roof
			icon='Skyscraper.dmi'
			icon_state="Glass"
			density=1
			Grabbable=0
		RoofGlass
			icon='Objects.dmi'
			icon_state="Glass"
			density=1
			Grabbable=0


	IconsXLBig
		icon='NewOther.dmi'
		Icon1
			icon_state="1"
		Icon2
			icon_state="2"
		Icon3
			icon_state="3"
		Icon4
			icon_state="4"
		Icon5
			icon_state="5"
		Icon6
			icon_state="6"
		Icon7
			icon_state="7"
		Icon8
			icon_state="8"
		Icon9
			icon_state="9"
		Icon10
			icon_state="10"
		Icon11
			icon_state="11"
		Icon12
			icon_state="12"
		Icon13
			icon_state="13"
		Icon14
			icon_state="14"
		Icon15
			icon_state="15"
		Icon16
			icon_state="16"
		Icon17
			icon_state="17"
		Icon18
			icon_state="18"
		Icon19
			icon_state="19"
		Icon20
			icon_state="20"
		Icon21
			icon_state="21"
		Icon22
			icon_state="22"
		Icon23
			icon_state="23"
		Icon24
			icon_state="24"
		Icon25
			icon_state="25"
		Icon26
			icon_state="26"
		Icon27
			icon_state="27"
		Icon28
			icon_state="28"
		Icon29
			icon_state="29"
		Icon30
			icon_state="30"
		Icon31
			icon_state="31"
		Icon32
			icon_state="32"
		Icon33
			icon_state="33"
		Icon34
			icon_state="34"
		Icon35
			icon_state="35"
		Icon36
			icon_state="36"
		Icon37
			icon_state="37"
		Icon38
			icon_state="38"
		Icon39
			icon_state="39"
		Icon40
			icon_state="40"
		Icon41
			icon_state="41"
		Icon42
			icon_state="42"
		Icon43
			icon_state="43"
		Icon44
			icon_state="44"
		Icon45
			icon_state="45"
		Icon46
			icon_state="46"
		Icon47
			icon_state="47"
		Icon48
			icon_state="48"
		Icon49
			icon_state="49"
		Icon50
			icon_state="50"
		Icon51
			icon_state="51"
		Icon52
			icon_state="52"
		Icon53
			icon_state="53"
		Icon54
			icon_state="54"
		Icon55
			icon_state="55"
		Icon56
			icon_state="56"
		Icon57
			icon_state="57"
		Icon58
			icon_state="58"
		Icon59
			icon_state="59"
		Icon60
			icon_state="60"
		Icon61
			icon_state="61"
		Icon62
			icon_state="62"
		Icon63
			icon_state="63"
		Icon64
			icon_state="64"
		Icon65
			icon_state="65"
		Icon66
			icon_state="66"
		Icon67
			icon_state="67"
		Icon68
			icon_state="68"
		Icon69
			icon_state="69"
		Icon70
			icon_state="70"
		Icon71
			icon_state="71"
		Icon72
			icon_state="72"
		Icon73
			icon_state="73"
			layer = MOB_LAYER+1
			density=1
		Icon74
			icon_state="74"
			layer = MOB_LAYER+1
			density=1
		Icon75
			icon_state="75"
			layer = MOB_LAYER+1
			density=1

	IconsX
		icon='NewObjects.dmi'
		Icon1
			icon_state="1"
			density=1
		Icon2
			icon_state="2"
			density=1
		Icon3
			icon_state="3"
			density=1
		Icon4
			icon_state="4"
			density=1
		Icon5
			icon_state="5"
			density=1
		Icon6
			icon_state="6"
			density=1
		Icon7
			icon_state="7"
			density=1
		Icon8
			icon_state="8"
		Icon9
			icon_state="9"
		Icon10
			icon_state="10"
		Icon11
			icon_state="11"
			density=1
		Icon12
			icon_state="12"
			density=1
		Icon13
			icon_state="13"
			density=1
		Icon14
			icon_state="14"
			density=1
		Icon15
			icon_state="15"
			density=1
		Icon16
			icon_state="16"
			density=1
		Icon17
			icon_state="17"
			density=1
		Icon18
			icon_state="18"
			density=1
		Icon19
			icon_state="19"
			density=1
		Icon20
			icon_state="20"
		Icon21
			icon_state="21"
		Icon22
			icon_state="22"
		Icon23
			icon_state="23"
		Icon24
			icon_state="24"
		Icon25
			icon_state="25"
			density=1
		Icon26
			icon_state="26"
			density=1
		Icon27
			icon_state="27"
		Icon28
			icon_state="28"
			density=1
			layer = MOB_LAYER+1
		Icon29
			icon_state="29"
			density=1
		Icon30
			icon_state="30"
			density=1
		Icon31
			icon_state="31"
			density=1
		Icon32
			icon_state="32"
			density=1
		Icon33
			icon_state="33"
			density=1
		Icon34
			icon_state="34"
			density=1
		Icon35
			icon_state="35"
			density=1
		Icon36
			icon_state="36"
			density=1
		Icon37
			icon_state="37"
			density=1
		Icon38
			icon_state="38"
		Icon39
			icon_state="39"
		Icon40
			icon_state="40"
		Icon41
			icon_state="41"
		Icon42
			icon_state="42"
			density=1
		Icon43
			icon_state="43"
			density=1
		Icon44
			icon_state="44"
			density=1
		Icon45
			icon_state="45"
			density=1
		Icon46
			icon_state="46"
			density=1
		Icon47
			icon_state="47"
			density=1
		Icon48
			icon_state="48"
			density=1
		Icon49
			icon_state="49"
			density=1
		Icon50
			icon_state="50"
			density=1
		Icon51
			icon_state="51"
			density=1
		Icon52
			icon_state="52"
			density=1
		Icon53
			icon_state="53"
			density=1
		Icon54
			icon_state="54"
			density=1
		Icon55
			icon_state="55"
			density=1
		Icon56
			icon_state="56"
		Icon57
			icon_state="57"
		Icon58
			icon_state="58"
		Icon59
			icon_state="59"
		Icon60
			icon_state="60"
		Icon61
			icon_state="61"
		Icon62
			icon_state="62"
		Icon63
			icon_state="63"
		Icon64
			icon_state="64"
		Icon65
			icon_state="65"
		Icon66
			icon_state="66"
		Icon67
			icon_state="67"
		Icon68
			icon_state="68"
		Icon69
			icon_state="69"
		Icon70
			icon_state="70"
		Icon71
			icon_state="71"
		Icon72
			icon_state="72"
		Icon73
			icon_state="73"
		Icon74
			icon_state="74"
		Icon75
			icon_state="75"
		Icon76
			icon_state="76"
		Icon77
			icon_state="77"
		Icon78
			icon_state="78"
			density=1
		Icon79
			icon_state="79"
		Icon80
			icon_state="80"
		Icon81
			icon_state="81"
		Icon82
			icon_state="82"
		Icon83
			icon_state="83"
			density=1
		Icon84
			icon_state="84"
			density=1
		Icon85
			icon_state="85"
			density=1
		Icon86
			icon_state="86"
			density=1
		Icon87
			icon_state="87"
		Icon88
			icon_state="88"
		Icon89
			icon_state="89"
		Icon90
			icon_state="90"
		Icon91
			icon_state="91"
			density=1
		Icon92
			icon_state="92"
		Icon93
			icon_state="93"
			density=1
		Icon94
			icon_state="94"
			density=1
		Icon95
			icon_state="95"
		Icon96
			icon_state="96"
		Icon97
			icon_state="97"
		Icon98
			icon_state="98"
			density=1
		Icon99
			icon_state="99"
		Icon100
			icon_state="100"
		Icon101
			icon_state="101"
			density=1
		Icon102
			icon_state="102"
			density=1
		Icon103
			icon_state="103"
		Icon104
			icon_state="104"
		Icon105
			icon_state="105"
		Icon106
			icon_state="106"
		Icon107
			icon_state="107"
		Icon108
			icon_state="108"
		Icon109
			icon_state="109"
		Icon110
			icon_state="110"
		Icon111
			icon_state="111"
		Icon112
			icon_state="112"
			density=1
		Icon113
			icon_state="113"
			density=1
		Icon114
			icon_state="114"
			density=1
		Icon115
			icon_state="115"
			density=1
		Icon116
			icon_state="116"
		Icon117
			icon_state="117"
		Icon118
			icon_state="118"
		Icon119
			icon_state="119"
		Icon120
			icon_state="120"
		Icon121
			icon_state="121"
			density=1
		Icon122
			icon_state="122"
			density=1
		Icon123
			icon_state="123"
		Icon124
			icon_state="124"
		Icon125
			icon_state="125"
			density=1
		Icon126
			icon_state="126"
		Icon127
			icon_state="127"
			density=1
		Icon128
			icon_state="128"
			density=1
		Icon129
			icon_state="129"
			density=1
		Icon130
			icon_state="130"
			density=1
		Icon131
			icon_state="131"
			density=1
		Icon132
			icon_state="132"
			layer = MOB_LAYER-1
		Icon133
			icon_state="133"
		Icon134
			icon_state="134"
		Icon135
			icon_state="135"
		Icon136
			icon_state="136"
		Icon137
			icon_state="137"
		Icon138
			icon_state="138"
		Icon139
			icon_state="139"
		Icon140
			icon_state="140"
		Icon141
			icon_state="141"
			density=1
		Icon142
			icon_state="142"
		Icon143
			icon_state="143"
			density=1
		Icon144
			icon_state="144"
		Icon145
			icon_state="145"
			density=1
		Icon146
			icon_state="146"
			density=1
		Icon147
			icon_state="147"
			density=1
		Icon148
			icon_state="148"
		Icon149
			icon_state="149"
		Icon150
			icon_state="150"
		Icon151
			icon_state="151"
		Icon152
			icon_state="152"
			density=1
		Icon153
			icon_state="153"
			density=1
		Icon154
			icon_state="154"
		Icon155
			icon_state="155"
			density=1
		Icon156
			icon_state="156"
			density=1
		Icon157
			icon_state="157"
			density=1
		Icon158
			icon_state="158"
		Icon159
			icon_state="159"
			density=1
		Icon160
			icon_state="160"
			density=1
		Icon161
			icon_state="161"
			density=1
		Icon162
			icon_state="162"
		Icon163
			icon_state="163"
		Icon164
			icon_state="164"
		Icon165
			icon_state="165"
		Icon166
			icon_state="166"
		Icon167
			icon_state="167"
		Icon168
			icon_state="168"
		Icon169
			icon_state="169"
		Icon170
			icon_state="170"
		Icon171
			icon_state="171"
		Icon172
			icon_state="172"
		Icon173
			icon_state="173"
		Icon174
			icon_state="174"
		Icon175
			icon_state="175"
		Icon176
			icon_state="176"

	MidgarObj
		MidgarBarrel
			icon='Midgar Tiles.dmi'
			icon_state="IndusBarrel"
			density=1
		MidgarCrane
			icon='Midgar Tiles.dmi'
			icon_state="Induscrane"
			layer= 5
		MidgarLaser
			icon='Midgar Tiles.dmi'
			icon_state="Induslaz1"
		MidgarLaser2
			icon='Midgar Tiles.dmi'
			icon_state="Induslaz11"
		MidgarLaser3
			icon='Midgar Tiles.dmi'
			icon_state="Induslaz2"
		MidgarLaser4
			icon='Midgar Tiles.dmi'
			icon_state="Induslaz22"
		MidgarLaser5
			icon='Midgar Tiles.dmi'
			icon_state="Induslaz"
		Midgarchest
			icon='Midgar Tiles.dmi'
			icon_state="IndusChest"
			density=1
		StreetLamp
			icon='Stret Laump.dmi'
			Flammable = 1
			density=1
			layer=5
		Lampost
			icon='Lampost and chairs.dmi'
			icon_state="Lampost"
			Flammable = 1
			density=1
		Stool
			icon='Lampost and chairs.dmi'
			icon_state="Stool"
			Flammable = 1
			layer=4
		TV
			icon='Lampost and chairs.dmi'
			icon_state="Tv"
			Flammable = 1
			density=1
		Widescreen
			icon='Lampost and chairs.dmi'
			icon_state="Widescreen"
			Flammable = 1
			density=1
		SmallChairE
			icon='Lampost and chairs.dmi'
			icon_state="Small chairE"
			Flammable = 1
		SmallChairW
			icon='Lampost and chairs.dmi'
			icon_state="Small chairW"
			Flammable = 1
		BenchW
			icon='Lampost and chairs.dmi'
			icon_state="BenchW"
			Flammable = 1
		BenchE
			icon='Lampost and chairs.dmi'
			icon_state="BenchE"
			Flammable = 1
		Steelstool
			icon='Lampost and chairs.dmi'
			icon_state="Steel Stool"
			Flammable = 1
			layer=4
		PlushChair
			icon='Lampost and chairs.dmi'
			icon_state="Chair"
			Flammable = 1
	Sign
		icon='Objects.dmi'
		icon_state="Sign"
		density=1
		Click() if(desc) usr<<desc
		Information_Panel
			icon='Objects.dmi'
			icon_state="Sign2"
		Sign3
			icon='Objects.dmi'
			icon_state="Sign3"
		Sign4
			icon='Objects.dmi'
			icon_state="Sign4"
		Sign5
			icon='Objects.dmi'
			icon_state="Sign5"
		Sign6
			icon='Objects.dmi'
			icon_state="Sign6"
		SignGrave1
			icon='NewObjects.dmi'
			icon_state="129"
		verb/Bolt()
			set src in oview(1)
			if(x&&y&&z&&!Bolted)
				Bolted=1
				Shockwaveable=0
				range(20,src)<<"[usr] bolts the [src] to the ground."

				return
			if(Bolted) if(src.Builder=="[usr.real_name]")
				range(20,src)<<"[usr] unbolts the [src] from the ground."
				Bolted=0
				Shockwaveable=1

				return


	Rock
		icon='Gardening.dmi'
		icon_state="Rock1"
	LargeRock
		density=1
		icon='Gardening.dmi'
		icon_state="Rock2"
	SignTech1
		icon='Lab2.dmi'
		icon_state="WallDisplayA"
	SignTech2
		icon='Lab2.dmi'
		icon_state="WallDisplayB"
	VineWallOL1
		icon='TurfOverlays.dmi'
		icon_state="vinewall1"
	VineWallOL2
		icon='TurfOverlays.dmi'
		icon_state="vinewall2"
	VineWallOL3
		icon='Gardening.dmi'
		icon_state="Natural5"
	VineWallOL4
		icon='Gardening.dmi'
		icon_state="Natural6"
	VineWallOL5
		icon='Gardening.dmi'
		icon_state="Natural7"
	WallCrackOL1
		icon='TurfOverlays.dmi'
		icon_state="crack1"
	WallCrackOL2
		icon='TurfOverlays.dmi'
		icon_state="crack2"
	WallCrackOL3
		icon='TurfOverlays.dmi'
		icon_state="crack3"
	firewood
		icon='Gardening.dmi'
		icon_state="Firewood"
		density=1
	WaterRock
		density=1
		icon='Gardening.dmi'
		icon_state="Rock4"
	HellRock
		density=1
		icon='Gardening.dmi'
		icon_state="Hellrock1"
	HellRock2
		density=1
		icon='Gardening.dmi'
		icon_state="Hellrock2"
	HellRock3
		density=1
		icon='Gardening.dmi'
		icon_state="Hellrock3"
	LargeRock2
		density=1
		icon='Gardening.dmi'
		icon_state="Rock3"
	Rock1
		icon='Gardening.dmi'
		icon_state="Rock5"
		density=1
	Rock2
		icon='Gardening.dmi'
		icon_state="Rock6"
		density=1
	Stalagmite
		density=1
		icon='Gardening.dmi'
		icon_state="Stalagmite"
	Fence
		density=1
		icon='Gardening.dmi'
		icon_state="Fence"
	Rock3
		icon='Gardening.dmi'
		icon_state="Rock6"
		density=1
	Rock4
		icon='Gardening.dmi'
		icon_state="Rock7"
		density=1
	Flowers
		icon='Gardening.dmi'
		icon_state="FlowerBed"
	Rock6
		icon='Gardening.dmi'
		icon_state="Rock8"
		density=1
	Bush1
		icon='Gardening.dmi'
		icon_state="Bush1"
		density=1
	Bush2
		icon='Gardening.dmi'
		icon_state="Bush2"
		density=1
	Bush3
		icon='Gardening.dmi'
		icon_state="Bush3"
		density=1
	Bush4
		icon='Gardening.dmi'
		icon_state="Bush4"
		density=1
	Bush5
		icon='Gardening.dmi'
		icon_state="Bush5"
		density=1
	SnowBush
		icon='Gardening.dmi'
		icon_state="Bush6"
		density=1
	Plant12
		icon='Gardening.dmi'
		icon_state="Plant1"
		density=1
	Plant11
		icon='Gardening.dmi'
		icon_state="Plant2"
		density=1
	Plant10
		icon='Gardening.dmi'
		icon_state="Plant3"
		density=1
	Plant16
		icon='Gardening.dmi'
		icon_state="Flowers1"
	Plant15
		icon='Gardening.dmi'
		icon_state="Flowers2"
	Plant21
		icon='Gardening.dmi'
		icon_state="Natural3"
	Plant2
		icon='Gardening.dmi'
		icon_state="Plant4"
		density=1
	Plant3
		icon='Gardening.dmi'
		icon_state="Plant5"
	Plant4
		icon='Gardening.dmi'
		icon_state="Plant6"
	Plant5
		icon='Gardening.dmi'
		icon_state="Plant7"
	Plant13
		icon='Gardening.dmi'
		icon_state="Bush7"
	Plant14
		icon='Gardening.dmi'
		icon_state="Tree1"
		density=1
	Plant18
		icon='Gardening.dmi'
		icon_state="Tree2"
		density=1
	Plant6
		icon='Gardening.dmi'
		icon_state="Hellrock4"
		density=1
	Plant20
		icon='Gardening.dmi'
		icon_state="Hellrock5"
		density=1
	Plant19
		icon='Gardening.dmi'
		icon_state="Hellrock6"
		density=1
	Plant7
		icon='Gardening.dmi'
		icon_state="Tree3"
		density=1
	Plant8
		icon='Gardening.dmi'
		icon_state="Tree4"
		density=1
	Plant9
		icon='Gardening.dmi'
		icon_state="Tree5"
		density=1
	Console1
		icon='Technology32x64.dmi'
		icon_state="Console1"
		density=1
		bound_height=64
	Console2
		icon='Technology64x64.dmi'
		icon_state="LargeConsole1"
		density=1
		bound_width=64
		layer=3
		pixel_y=-20
	Console3
		icon='Technology64x64.dmi'
		icon_state="LargeConsole2"
		density=1
		bound_width=64
		layer=2
		pixel_y=-20
	Console4
		icon='Lab.dmi'
		icon_state="Lab1"
		density=1
	Console5
		icon='Lab.dmi'
		icon_state="Lab2"
		density=1
	Console6L
		icon='Lab.dmi'
		icon_state="PanelL"
		density=1
	Console6R
		icon='Lab.dmi'
		icon_state="PanelR"
		density=1
	Console6R2
		icon='Lab.dmi'
		icon_state="PanelR2"
		density=1
	Console6Top
		icon='Lab.dmi'
		icon_state="PanelTop"
		layer=4
	PipeNS
		icon='Lab.dmi'
		icon_state="pipes"
		dir=NORTH
	PipeWE
		icon='Lab.dmi'
		icon_state="pipes"
		dir=EAST
	TechObject1
		icon='ArtificalObj.dmi'
		icon_state="Fan"
		density=1
	TechObject2
		icon='ArtificalObj.dmi'
		icon_state="Vent"
		density=1
	FishTank1
		icon='Technology32x64.dmi'
		icon_state="FishTank1"
		density=1
		bound_height=64
	FishTank2
		icon='Technology64x64.dmi'
		icon_state="FishTank2"
		density=1
		bound_width=64
		layer=5
	Table7
		icon='Objects.dmi'
		icon_state="Table1"
		density=1
	Table8
		icon='Objects.dmi'
		icon_state="Table2"
		density=1
	Table9
		icon='Objects.dmi'
		icon_state="Table3"
		density=1
	Whirlpool
		icon='Gardening.dmi'
		icon_state="Natural1"
	bridgeN
		icon='Edges.dmi'
		icon_state="N"
		density=1
	bridgeS
		icon='Edges.dmi'
		icon_state="S"
		density=1
	bridgeE
		icon='Edges.dmi'
		icon_state="E"
		density=1
	bridgeW
		icon='Edges.dmi'
		icon_state="W"
		density=1
	Chest
		icon='Objects.dmi'
		icon_state="Chest"
	Lights_and_Shadows
		icon='lightsandshadows.dmi'
		icon_state="lighteffect2"
	HellPot
		icon='PotFixed.dmi'
		icon_state="Pot1"
		density=1

/*	RugLarge
		New()
			var/image/A=image(icon='Objects.dmi',icon_state="Rug1",pixel_x=-16,pixel_y=16,layer=MOB_LAYER-1)
			var/image/B=image(icon='Objects.dmi',icon_state="Rug2",pixel_x=16,pixel_y=16,layer=MOB_LAYER-1)
			var/image/C=image(icon='Objects.dmi',icon_state="Rug3",pixel_x=-16,pixel_y=-16,layer=MOB_LAYER-1)
			var/image/D=image(icon='Objects.dmi',icon_state="Rug4",pixel_x=16,pixel_y=-16,layer=MOB_LAYER-1)
			overlays.Remove(A,B,C,D)
			overlays.Add(A,B,C,D)
			..()*/
	Apples
		icon='Objects.dmi'
		icon_state="Apples"
	Book
		icon='Objects.dmi'
		icon_state="Book"
	Light
		icon='Objects.dmi'
		icon_state="Light"
		density=1
	Glass
		icon='Objects.dmi'
		icon_state="Glass"
		density=1
		layer=MOB_LAYER+1
/*	RoofGlass
		icon='Objects.dmi'
		icon_state="Glass"
		density=1
		opacity=0
		Grabbable=0
		Enter(atom/A)
			if(FlyOverAble||ghostDens_check(A)||(!A.density&&istype(A,/obj/items/Bomb))) return ..()
			else return*/
	Table6
		icon='Objects.dmi'
		icon_state="Table4"
		density=1
		layer=4
	Table5
		icon='Objects.dmi'
		icon_state="TableL"
		density=1
	Table3
		icon='Objects.dmi'
		icon_state="TableR"
		density=1
	Table4
		icon='Objects.dmi'
		icon_state="TableM"
		density=1
	Log
		density=1
		New()
			var/image/A=image(icon='Objects.dmi',icon_state="Log1",pixel_x=-16)
			var/image/B=image(icon='Objects.dmi',icon_state="Log2",pixel_x=16)
			overlays.Remove(A,B)
			overlays.Add(A,B)
			..()
	FancyCouch
		New()
			var/image/A=image(icon='Objects.dmi',icon_state="CouchL",pixel_x=-16)
			var/image/B=image(icon='Objects.dmi',icon_state="CouchR",pixel_x=16)
			overlays.Remove(A,B)
			overlays.Add(A,B)
			..()

	Jugs
		icon='Objects.dmi'
		icon_state="Jugs"
		density=1
	Hay
		icon='Objects.dmi'
		icon_state="Hay"
		density=1
	Clock
		icon='Objects.dmi'
		icon_state="Clock"
		density=1

	Waterpot
		icon='Objects.dmi'
		icon_state="PotWater"
		density=1

	Stove
		icon='Objects.dmi'
		icon_state="Stove"
		density=1
	Drawer
		icon='Objects.dmi'
		icon_state="Drawers"
		density=1
		New()
			var/image/A=image(icon='Objects.dmi',icon_state="DrawersT",pixel_y=32)
			overlays.Remove(A)
			overlays.Add(A)
			..()
	Bed
		icon='Objects.dmi'
		icon_state="BedT"
		New()
			var/image/A=image(icon='Objects.dmi',icon_state="Bed",pixel_y=-32)
			overlays.Remove(A)
			overlays.Add(A)
			..()
	LargeBed
		icon='LargeBed.dmi'
	Torch1
		icon='Objects.dmi'
		icon_state="Torch1"
		density=1
	Torch2
		icon='Objects.dmi'
		icon_state="Torch2"
		density=1
	Torch3
		icon='Objects.dmi'
		icon_state="Torch3"
		density=1
	Fire
		icon='Objects.dmi'
		icon_state="Fire"
		density=1
	barrel
		icon='Objects.dmi'
		icon_state="Barrel"
		density=1
	chair
		icon='Objects.dmi'
		icon_state="Chair"
	Stool
		icon='ArtificalObj.dmi'
		icon_state="Stool"
	box2
		icon='Objects.dmi'
		icon_state="Box"
		density=1

obj/Turfs/Trees
	SmallPine
		icon='Trees.dmi'
		icon_state="P2"
		density=1
		New()
			var/image/A=image(icon='Trees.dmi',icon_state="P5",pixel_y=0,pixel_x=32,layer=5)
			var/image/E=image(icon='Trees.dmi',icon_state="P1",pixel_y=0,pixel_x=-32,layer=5)
			var/image/B=image(icon='Trees.dmi',icon_state="P0",pixel_y=-32,pixel_x=0,layer=5)
			var/image/C=image(icon='Trees.dmi',icon_state="P3",pixel_y=32,pixel_x=-32,layer=5)
			var/image/D=image(icon='Trees.dmi',icon_state="P4",pixel_y=32,pixel_x=0,layer=5)
			overlays.Remove(A,B,C,D,E)
			overlays.Add(A,B,C,D,E)
			..()
	RedTree
		density=1
		New()
			var/image/A=image(icon='Trees.dmi',icon_state="R1",pixel_y=32,pixel_x=-32,layer=5)
			var/image/B=image(icon='Trees.dmi',icon_state="R2",pixel_y=0,pixel_x=0,layer=5)
			var/image/C=image(icon='Trees.dmi',icon_state="R3",pixel_y=32,pixel_x=32,layer=5)
			var/image/D=image(icon='Trees.dmi',icon_state="R4",pixel_y=0,pixel_x=-32,layer=5)
			var/image/E=image(icon='Trees.dmi',icon_state="R5",pixel_y=32,pixel_x=0,layer=5)
			var/image/F=image(icon='Trees.dmi',icon_state="R6",pixel_y=0,pixel_x=32,layer=5)
			overlays.Remove(A,B,C,D,E,F)
			overlays.Add(A,B,C,D,E,F)
			..()
	BigHousePlant
		density=1
		icon='Gardening.dmi'
		icon_state="Plant"
		New()
			var/image/A=image(icon='Gardening.dmi',icon_state="PlantT",pixel_y=32,pixel_x=0,layer=5)
			overlays.Remove(A)
			overlays.Add(A)
			..()
	Oak
		density=1
		New()
			var/image/A=image(icon='Trees.dmi',icon_state="Z1",pixel_y=0,pixel_x=-16,layer=5)
			var/image/B=image(icon='Trees.dmi',icon_state="Z2",pixel_y=0,pixel_x=16,layer=5)
			var/image/C=image(icon='Trees.dmi',icon_state="Z3",pixel_y=32,pixel_x=-16,layer=5)
			var/image/D=image(icon='Trees.dmi',icon_state="Z4",pixel_y=32,pixel_x=16,layer=5)
			var/image/E=image(icon='Trees.dmi',icon_state="Z5",pixel_y=64,pixel_x=-16,layer=5)
			var/image/F=image(icon='Trees.dmi',icon_state="Z6",pixel_y=64,pixel_x=16,layer=5)
			overlays.Remove(A,B,C,D,E,F)
			overlays.Add(A,B,C,D,E,F)
			..()
	RoundTree
		density=1
		New()
			var/image/A=image(icon='Trees.dmi',icon_state="01",pixel_y=0,pixel_x=-16,layer=5)
			var/image/B=image(icon='Trees.dmi',icon_state="02",pixel_y=0,pixel_x=16,layer=5)
			var/image/C=image(icon='Trees.dmi',icon_state="03",pixel_y=32,pixel_x=-16,layer=5)
			var/image/D=image(icon='Trees.dmi',icon_state="04",pixel_y=32,pixel_x=16,layer=5)
			overlays.Remove(A,B,C,D)
			overlays.Add(A,B,C,D)
			..()
	Tree
		density=1
		icon='Trees.dmi'
		icon_state="Bottom"
		New()
			var/image/B=image(icon='Trees.dmi',icon_state="Middle",pixel_y=32,pixel_x=0,layer=5)
			var/image/C=image(icon='Trees.dmi',icon_state="Top",pixel_y=64,pixel_x=0,layer=5)
			overlays.Remove(B,C)
			overlays.Add(B,C)
			..()
	Palm
		density=1
		New()
			var/image/A=image(icon='Trees.dmi',icon_state="A1",pixel_y=0,pixel_x=-16,layer=5)
			var/image/B=image(icon='Trees.dmi',icon_state="A2",pixel_y=0,pixel_x=16,layer=5)
			var/image/C=image(icon='Trees.dmi',icon_state="A3",pixel_y=32,pixel_x=-16,layer=5)
			var/image/D=image(icon='Trees.dmi',icon_state="A4",pixel_y=32,pixel_x=16,layer=5)
			var/image/E=image(icon='Trees.dmi',icon_state="A5",pixel_y=64,pixel_x=-16,layer=5)
			var/image/F=image(icon='Trees.dmi',icon_state="A6",pixel_y=64,pixel_x=16,layer=5)
			var/image/G=image(icon='Trees.dmi',icon_state="A7",pixel_y=96,pixel_x=-16,layer=5)
			var/image/H=image(icon='Trees.dmi',icon_state="A8",pixel_y=96,pixel_x=16,layer=5)
			overlays.Remove(A,B,C,D,E,F,G,H)
			overlays.Add(A,B,C,D,E,F,G,H)
			..()
	LargePine
		density=1
		New()
			var/image/A=image(icon='Trees.dmi',icon_state="X1",pixel_y=0,pixel_x=-16,layer=5)
			var/image/B=image(icon='Trees.dmi',icon_state="X2",pixel_y=0,pixel_x=16,layer=5)
			var/image/C=image(icon='Trees.dmi',icon_state="X3",pixel_y=32,pixel_x=-16,layer=5)
			var/image/D=image(icon='Trees.dmi',icon_state="X4",pixel_y=32,pixel_x=16,layer=5)
			var/image/E=image(icon='Trees.dmi',icon_state="X5",pixel_y=64,pixel_x=-16,layer=5)
			var/image/F=image(icon='Trees.dmi',icon_state="X6",pixel_y=64,pixel_x=16,layer=5)
			overlays.Remove(A,B,C,D,E,F)
			overlays.Add(A,B,C,D,E,F)
			..()
	LargePineSnow
		density=1
		New()
			var/image/A=image(icon='Trees.dmi',icon_state="S1",pixel_y=0,pixel_x=-16,layer=5)
			var/image/B=image(icon='Trees.dmi',icon_state="S2",pixel_y=0,pixel_x=16,layer=5)
			var/image/C=image(icon='Trees.dmi',icon_state="S3",pixel_y=32,pixel_x=-16,layer=5)
			var/image/D=image(icon='Trees.dmi',icon_state="S4",pixel_y=32,pixel_x=16,layer=5)
			var/image/E=image(icon='Trees.dmi',icon_state="S5",pixel_y=64,pixel_x=-16,layer=5)
			var/image/F=image(icon='Trees.dmi',icon_state="S6",pixel_y=64,pixel_x=16,layer=5)
			overlays.Remove(A,B,C,D,E,F)
			overlays.Add(A,B,C,D,E,F)
			..()
	RedPine
		density=1
		New()
			var/image/A=image(icon='Trees.dmi',icon_state="A1",pixel_y=0,pixel_x=-16,layer=5)
			var/image/B=image(icon='Trees.dmi',icon_state="A2",pixel_y=0,pixel_x=16,layer=5)
			var/image/C=image(icon='Trees.dmi',icon_state="A3",pixel_y=32,pixel_x=-16,layer=5)
			var/image/D=image(icon='Trees.dmi',icon_state="A4",pixel_y=32,pixel_x=16,layer=5)
			var/image/E=image(icon='Trees.dmi',icon_state="A5",pixel_y=64,pixel_x=-16,layer=5)
			var/image/F=image(icon='Trees.dmi',icon_state="A6",pixel_y=64,pixel_x=16,layer=5)
			overlays.Remove(A,B,C,D,E,F)
			overlays.Add(A,B,C,D,E,F)
			..()

	NamekTree
		density=1
		New()
			overlays=null
			switch(pick(1,2,3,4))
				if(1)
					var/image/A=image(icon='Trees.dmi',icon_state="NT2",pixel_y=0,layer=5)
					var/image/B=image(icon='Trees.dmi',icon_state="NT1")
					overlays.Add(A,B)
				if(2)
					var/image/A=image(icon='Trees.dmi',icon_state="Bottom1")
					var/image/B=image(icon='Trees.dmi',icon_state="Middle1",pixel_y=32)
					var/image/C=image(icon='Trees.dmi',icon_state="Top1",pixel_y=64)
					overlays.Add(A,B,C)
				if(3)
					var/image/A=image(icon='Trees.dmi',icon_state="T0")
					var/image/B=image(icon='Trees.dmi',icon_state="T1",pixel_y=32)
					var/image/C=image(icon='Trees.dmi',icon_state="T2",pixel_y=64)
					var/image/D=image(icon='Trees.dmi',icon_state="T3",pixel_y=64,pixel_x=32)
					overlays.Add(A,B,C,D)
				if(4)
					var/image/A=image(icon='Trees.dmi',icon_state="N1")
					var/image/B=image(icon='Trees.dmi',icon_state="N2",pixel_y=32)
					var/image/C=image(icon='Trees.dmi',icon_state="N3",pixel_y=64)
					var/image/D=image(icon='Trees.dmi',icon_state="N4",pixel_y=32,pixel_x=32)
					var/image/E=image(icon='Trees.dmi',icon_state="N5",pixel_y=64,pixel_x=32)
					overlays.Add(A,B,C,D,E)
			..()

obj/Blocker
	EarthPrison
		icon='Roofs.dmi'
		icon_state="Roof5"
		Grabbable=0
		Savable=0
		density=1
		opacity=1
		Enter(atom/A)
			if(ghostDens_check(A)) return ..()
			else return 0
		Cross(atom/A)
			if(ghostDens_check(A)) return ..()
			else return 0


turf/Special
	Buildable=0
	Blank
		opacity=1
		FlyOverAble=0
		density=1
		Health=1.#INF
		Enter(mob/A)
			if(ismob(A)) if(A.client)
				if(A.client.holder)
					return ..()
				else
					return 0
			else return 0//why was this del(A)
			if(ismob(A)) return 0
			else return 0//why was this del(A)

/*
	CaveEntrance
		Health=1.#INF
		icon='Special.dmi'
		icon_state="Special4"*/
	PDTurf
		icon='PDTurf.dmi'
		icon_state="1"
	Static
		icon='Special.dmi'
		icon_state="Special5"
	Stars
		icon = 'StarPixel.dmi'
		icon_state="2"
		Health=1.#INF
	EventStars
		icon='StarPixel.dmi'
		icon_state="3"
		Health=1.#INF
	BiodomeGlass
		icon='Objects.dmi'
		icon_state="Glass"
		Health=5000000
		density=1
		opacity=0
		Enter(atom/A)
			if(ghostDens_check(A)||(!A.density&&istype(A,/obj/items/Bomb)))if(!istype(A,/obj/TrainingEq)) return ..()
			else return



//	DemonWorldPortal
//		icon='Demon World Test.dmi'
//		Health=9999999999999999999999999999999999999999999999
/*

	Tech5T
		icon='Special.dmi'
		icon_state="Tech5T"
	Tech5TB
		icon='Special.dmi'
		icon_state="Tech5TB"


	DiveSword
		var/typee
		var/antispam
		density=1
		icon='Doors.dmi'
		icon_state="Closed1"
		New()
			Open()
			src.antispam=null
			..()
		Click()
			..()
			if(usr.DiveLock)
				usr<<"Finish picking or giving up before clicking another one."
				return
			if(!usr.DiveWeapon)
				if(usr in oview(1,src))
					usr.DiveLock=1
					if(usr.Alert("Are you sure you want to pick the sword?"))
						usr.DiveWeapon="Sword"
						usr.ComboPlus=1
						usr << "Your path is set."
						usr << "Now...what will you give up in exchange?"
						usr.StrengthMod*=1.25
						usr.Strength*=1.25
						usr.ForceMod*=1.25
						usr.Force*=1.25
						usr.OffenseMod*=1.25
						usr.Offense*=1.25
						usr.DiveLock=0
						return
					usr.DiveLock=0
			else if(usr.DiveWeapon)
				if(usr.DiveWeapon=="Sword")
					usr << "Can't let you give up what you've got, Riku."
					return
				if(usr.Alert("Are you sure you want to give up the sword?"))
					usr.DiveAbandon="Sword"
					usr << "Your journey begins in the dead of night."
					usr << "Your road won't be easy, but a rising sun awaits you at the end."
					usr.StrengthMod/=1.25
					usr.Strength/=1.25
					usr.ForceMod/=1.25
					usr.Force/=1.25
					usr.OffenseMod/=1.25
					usr.Offense/=1.25
					usr.loc = locate(usr.PrevX, usr.PrevY, usr.PrevZ)
					/*usr.contents+=new/obj/Skills/Keyblade/CallKeyblade
					usr.contents+=new/obj/Skills/Keyblade/BestowKeyblade*/
	DiveShield
		var/typee
		var/antispam
		density=1
		icon='Doors.dmi'
		icon_state="Closed1"
/*		New()
			Open()
			src.antispam=null
			..()*/
		Click()
			..()
			if(usr.DiveLock)
				usr<<"Finish picking or giving up before clicking another one."
				return
			if(!usr.DiveWeapon)
				if(usr in oview(1,src))
					usr.DiveLock=1
					if(usr.Alert("Are you sure you want to pick the shield?"))
						usr.DiveWeapon="Shield"
						usr.SecondChance=1
						usr << "Your path is set."
						usr << "Now...what will you give up in exchange?"
						usr.EnduranceMod*=1.15
						usr.Endurance*=1.15
						usr.ResistanceMod*=1.15
						usr.Resistance*=1.15
						usr.DefenseMod*=1.15
						usr.Defense*=1.15
						usr.DiveLock=0
						return
					usr.DiveLock=0
			else if(usr.DiveWeapon)
				if(usr.DiveWeapon=="Shield")
					usr << "Can't let you give up what you've got, Kairi."
					return
				if(usr.Alert("Are you sure you want to give up the shield?"))
					usr.DiveAbandon="Shield"
					usr << "Your journey begins at dawn."
					usr << "As long as the sun is shining, your journey should be a pleasant one."
					usr.EnduranceMod/=1.15
					usr.Endurance/=1.15
					usr.ResistanceMod/=1.15
					usr.Resistance/=1.15
					usr.DefenseMod/=1.15
					usr.Defense/=1.15
					usr.loc = locate(usr.PrevX, usr.PrevY, usr.PrevZ)
					/*usr.contents+=new/obj/Skills/Keyblade/CallKeyblade
					usr.contents+=new/obj/Skills/Keyblade/BestowKeyblade*/
	DiveStaff
		var/typee
		var/antispam
		density=1
		icon='Doors.dmi'
		icon_state="Closed1"
/*		New()
			Open()
			src.antispam=null
			..()*/
		Click()
			..()
			if(usr.DiveLock)
				usr<<"Finish picking or giving up before clicking another one."
				return
			if(!usr.DiveWeapon)
				if(usr in oview(1,src))
					usr.DiveLock=1
					if(usr.Alert("Are you sure you wish to choose the staff?"))
						usr.DiveWeapon="Staff"
						usr.MPRage=1
						usr << "Your path is set."
						usr << "Now...what will you give up in exchange?"
						usr.Recovery*=1.25
						usr.EnergyMod*=1.5
						usr.EnergyMax*=1.5
						usr.Energy*=1.5
						usr.DiveLock=0
						return
					usr.DiveLock=0
			else if(usr.DiveWeapon)
				if(usr.DiveWeapon=="Staff")
					usr << "Can't let you give up what you've got, Sora."
					return
				if(usr.Alert("Are you sure you want to give up the staff?"))
					usr.DiveAbandon="Staff"
					if(usr.Alert("Are you sure you wish to abandon the staff?"))
						usr.DiveAbandon="Staff"
						usr << "Your journey begins at midday."
						usr << "Keep a steady pace, and you'll come through fine."
						usr.Recovery/=1.25
						usr.EnergyMod/=1.5
						usr.EnergyMax/=1.5
						usr.Energy/=1.5
						usr.loc = locate(usr.PrevX, usr.PrevY, usr.PrevZ)
						/*usr.contents+=new/obj/Skills/Keyblade/CallKeyblade
						usr.contents+=new/obj/Skills/Keyblade/BestowKeyblade*/ */

	Orb
		icon='Special.dmi'
		icon_state="Special8"
		density=0
	Ladder
		icon='Special.dmi'
		icon_state="Special3"
		density=0
	Sky1
		icon='Special.dmi'
		icon_state="Special2"
	/*	Enter(mob/M)
			if(!Builder&&ismob(M)&&prob(20)&&(!M.Flying||M.density)) M.z=5
			M.Health-=20
			M<< "You fell from the sky...!?"
			return ..()*/
	Sky2
		icon='Special.dmi'
		icon_state="Special1"
		density=1
/*
	Ichor_Water
		icon='Ichor Turf.dmi'
		icon_state="water"
		density=0
		Flammable=1
	Midgar_Ichor
		icon='Ichor Turf.dmi'
		icon_state="ground"
		Flammable=1
	Midgar_IchorWall
		icon='Ichor Turf.dmi'
		icon_state="wall"
		density=1
		Flammable=1
	MidgarIchorW
		icon='Ichor Turf.dmi'
		icon_state="edgeW"
		density=0
	MidgarIchorS
		icon='Ichor Turf.dmi'
		icon_state="edgeS"
		density=0
	MidgarIchorE
		icon='Ichor Turf.dmi'
		icon_state="edgeE"
		density=0
	MidgarIchorN
		icon='Ichor Turf.dmi'
		icon_state="edgeN"
		density=0
		Flammable=1
	BigTrainEngineR
		icon='Train Large.dmi'
		icon_state="EngineR"
		density=1
		layer=4
		Flammable=1
	BigTrainEngineL
		icon='Train Large.dmi'
		icon_state="EngineL"
		density=1
		layer=4
		Flammable=1
	BigTrainCarrageR
		icon='Train Large.dmi'
		icon_state="CarrageR"
		density=1
		layer=4
		Flammable=1
	BigTrainCarrageL
		icon='Train Large.dmi'
		icon_state="CarrageL"
		density=1
		layer=4
		Flammable=1
	midgarTrainFloor
		icon='TrainInterior.dmi'
		icon_state="trainFloorAnim"
		density=0
		layer=1
		Flammable=1
	midgarTrainGrate
		icon='TrainInterior.dmi'
		icon_state="trainFloorGrateAnim"
		density=0
		Flammable=1
	midgarTrainPole
		icon='TrainInterior.dmi'
		icon_state="tPoleBotAnim"
		density=1
		Flammable=1
	midgarTrainPoleTop
		icon='TrainInterior.dmi'
		icon_state="tPoleTopAnim"
		density=0
		layer=5
		Flammable=1
	midgarTrainBenchTop
		icon='TrainInterior.dmi'
		icon_state="tBenchAnim"
		density=0
		layer=1
		Flammable=1
	midgarTrainBenchBottom
		icon='TrainInterior.dmi'
		icon_state="rTBenchAnim"
		density=0
		layer=5
		Flammable=1
	midgarBench
		icon='TrainInterior.dmi'
		icon_state="bench"
		density=0
		layer=4
		Flammable=1
	MidgarTrackAnim
		icon='trackanim.dmi'
		icon_state="Animation"
		density=0
		Flammable=1
	MidgarTrackAnim2
		icon='trackanim.dmi'
		icon_state="Animation2"
		density=0
		Flammable=1


// JENOVA STUFF//
	jenovaReactorBLeft
		icon='Jenova stuff.dmi'
		icon_state="bLeft"
		density=0
		Flammable=1

	jenovaReactorBRight
		icon='Jenova stuff.dmi'
		icon_state="bRight"
		density=0
		Flammable=1

	jenovaReactorCLeft
		icon='Jenova stuff.dmi'
		icon_state="mLeft"
		density=0
		Flammable=1

	jenovaReactorCRight
		icon='Jenova stuff.dmi'
		icon_state="mRight"
		density=0
		Flammable=1

	jenovaReactorTLeft
		icon='Jenova stuff.dmi'
		icon_state="tLeft"
		density=0
		Flammable=1

	jenovaReactorTRight
		icon='Jenova stuff.dmi'
		icon_state="tRight"
		density=0
		Flammable=1

	jenovaReactorBRight
		icon='Jenova stuff.dmi'
		icon_state="bRight"
		density=0
		Flammable=1

	jenovaReactorBLeft
		icon='Jenova stuff.dmi'
		icon_state="bLeft"
		density=0
		Flammable=1

	jenovaTankB
		icon='Jenova stuff.dmi'
		icon_state="tankBottom"
		density=0
		layer=4
		Flammable=1

	jenovaTankC
		icon='Jenova stuff.dmi'
		icon_state="tankMiddle"
		density=0
		layer=4
		Flammable=1

	jenovaTankT
		icon='Jenova stuff.dmi'
		icon_state="tankTop"
		density=0
		layer=4
		Flammable=1

	jenovaBG
		icon='KelvinReactor.dmi'
		icon_state="Jenova BG"
		density=0
		Flammable=1
*/
turf/Special

	Buildable=0

	Teleporter2
		density=1
		var/gotox
		var/gotoy
		var/gotoz
		Enter(mob/M) M.loc=locate(gotox,gotoy,gotoz)
		Health=1.#INF

	ArdentPortals
		icon='Lab.dmi'
		icon_state="Warp"
		Health=1.#INF
		density=1
		Portal1In
			Enter(mob/M) M.loc=locate(/turf/Special/ArdentPortals/Portal1Out)
		Portal1Out
			Enter(mob/M) M.loc=locate(/turf/Special/ArdentPortals/Portal1In)
		Portal2In
			Enter(mob/M) M.loc=locate(/turf/Special/ArdentPortals/Portal2Out)
		Portal2Out
			Enter(mob/M) M.loc=locate(/turf/Special/ArdentPortals/Portal2In)


	IceBreakerPortals
		icon='Lab.dmi'
		icon_state="Warp"
		Health=1.#INF
		density=1
		Portal1In
			Enter(mob/M) M.loc=locate(/turf/Special/IceBreakerPortals/Portal1Out)
		Portal1Out
			Enter(mob/M) M.loc=locate(/turf/Special/IceBreakerPortals/Portal1In)
		Portal2In
			Enter(mob/M) M.loc=locate(/turf/Special/IceBreakerPortals/Portal2Out)
		Portal2Out
			Enter(mob/M) M.loc=locate(/turf/Special/IceBreakerPortals/Portal2In)

/*		SpecialTele
			GoAbove
			GoBelow


//yellow purple cyan
mob/var
	Teacher
	Judgement
	AfterlifeFaction


			GoDeep
			GoHigh */
//		icon='lightsandshadows.dmi'
/*		Bump(/obj/Items/Tech/SpaceTravel/A)
			if(istype(A,/obj/Items/Tech/SpaceTravel))
				A.loc=locate(gotoX,gotoY,gotoZ)
			else
				return*/
//	PlanetLooper
//		density=1
//		Health=9999999999999999999999999999999999999999999999
//		LogPEndurance=10000000000000000000


/*
obj/Special

	StaticSurf
		icon='Special.dmi'
		icon_state="Special5S"

	midgarTrainWallBottom
		icon='TrainInterior.dmi'
		icon_state="tWallBotAnim"
		density=1
		layer=3
		Health=6957830578348905734057340
		Flammable = 1

	shinraLogo
		icon='Shinra.png'
		density=0
		layer=3
		Health=6957830578348905734057340
		Flammable = 1

	JENOVA
		icon='Jenova stuff.dmi'
		icon_state="JENOVA"
		density=0
		layer=3
		Flammable = 1

	Taxi1
		icon='tcab.dmi'
		icon_state="taxiR"
		density=1
		layer=3
		Flammable = 1

	Taxi2
		icon='tcab.dmi'
		icon_state="taxiL"
		density=1
		layer=3
		Flammable = 1

	soldierLogo
		icon='soldierlogo.png'
		density=0
		layer=3
		Health=6957830578348905734057340
		Flammable = 1

	//Luna attempting to make a special Object you cannot fly over.//
	midgarTrainWallTop
		icon='TrainInterior.dmi'
		icon_state="tWallTopAnim"
		density=1
		opacity=0
		layer=3
		Health=6957830578348905734057340

		Flammable = 1
*/
obj/Turfs/Edges
	RockEdgeN
		icon='Edges.dmi'
		icon_state="1"
		density=1
		dir=NORTH
	RockEdgeS
		icon='Edges.dmi'
		icon_state="1"
		density=1
		dir=SOUTH
	RockEdgeW
		icon='Edges.dmi'
		icon_state="1"
		density=1
		dir=WEST
	RockEdgeE
		icon='Edges.dmi'
		icon_state="1"
		density=1
		dir=EAST
	RockEdge2N
		icon='Edges.dmi'
		icon_state="2"
		density=1
		dir=NORTH
	RockEdge2S
		icon='Edges.dmi'
		icon_state="2"
		density=1
		dir=SOUTH
	RockEdge2W
		icon='Edges.dmi'
		icon_state="2"
		density=1
		dir=WEST
	RockEdge2E
		icon='Edges.dmi'
		icon_state="2"
		density=1
		dir=EAST
	Edge3N
		icon='Edges.dmi'
		icon_state="3"
		density=1
		dir=NORTH
	Edge3S
		icon='Edges.dmi'
		icon_state="3"
		density=1
		dir=SOUTH
	Edge3W
		icon='Edges.dmi'
		icon_state="3"
		density=1
		dir=WEST
	Edge3E
		icon='Edges.dmi'
		icon_state="3"
		density=1
		dir=EAST
	Edge4N
		icon='Edges.dmi'
		icon_state="4"
		density=1
		dir=NORTH
	Edge4S
		icon='Edges.dmi'
		icon_state="4"
		density=1
		dir=SOUTH
	Edge4W
		icon='Edges.dmi'
		icon_state="4"
		density=1
		dir=WEST
	Edge4E
		icon='Edges.dmi'
		icon_state="4"
		density=1
		dir=EAST
	Edge5N
		icon='Edges.dmi'
		icon_state="5"
		density=1
		dir=NORTH
	Edge5S
		icon='Edges.dmi'
		icon_state="5"
		density=1
		dir=SOUTH
	Edge5W
		icon='Edges.dmi'
		icon_state="5"
		density=1
		dir=WEST
	Edge5E
		icon='Edges.dmi'
		icon_state="5"
		density=1
		dir=EAST
	Edge6N
		icon='Edges.dmi'
		icon_state="6"
		density=1
		dir=NORTH
	Edge6S
		icon='Edges.dmi'
		icon_state="6"
		density=1
		dir=SOUTH
	Edge6W
		icon='Edges.dmi'
		icon_state="6"
		density=1
		dir=WEST
	Edge6E
		icon='Edges.dmi'
		icon_state="6"
		density=1
		dir=EAST
	MetalEdgeN
		icon='Edges.dmi'
		icon_state="N2"
		density=1
		dir=NORTH
	MetalEdgeS
		icon='Edges.dmi'
		icon_state="S2"
		density=1
		dir=SOUTH
	MetalEdgeE
		icon='Edges.dmi'
		icon_state="E2"
		density=1
		dir=EAST
	MetalEdgeW
		icon='Edges.dmi'
		icon_state="W2"
		density=1
		dir=WEST
	DarkEdgeN
		icon='Edges.dmi'
		icon_state="N3"
		density=1
		dir=NORTH
	DarkEdgeS
		icon='Edges.dmi'
		icon_state="S3"
		density=1
		dir=SOUTH
	DarkEdgeE
		icon='Edges.dmi'
		icon_state="E3"
		density=1
		dir=EAST
	DarkEdgeW
		icon='Edges.dmi'
		icon_state="W3"
		density=1
		dir=WEST
	GrayEdgeN
		icon='Edges.dmi'
		icon_state="7"
		density=1
		dir=NORTH
	GrayEdgeS
		icon='Edges.dmi'
		icon_state="7"
		density=1
		dir=SOUTH
	GrayEdgeE
		icon='Edges.dmi'
		icon_state="7"
		density=1
		dir=EAST
	GrayEdgeWest
		icon='Edges.dmi'
		icon_state="7"
		density=1
		dir=WEST


obj/Turfs/Surf
	icon='Surf.dmi'
	FireSurf
		icon_state="8"
	Water10Surf
		icon_state="1"
	Water10Surf2
		icon_state="1N"
	Water9Surf
		icon_state="6"
	Water9Surf2
		icon_state="6N"
	Water2Surf
		icon_state="2"
	Water2Surf2
		icon_state="2N"
	Water8Surf
		icon_state="4"
	Water8Surf2
		icon_state="4N"
	Water3Surf
		icon_state="3"
	Water3Surf2
		icon_state="3N"
	Water5Surf
		icon_state="5"
	Water5Surf2
		icon_state="5N"
	Water1Surf
		icon_state="7"
	Water1Surf2
		icon_state="7N"
	Water9Surf
		icon_state="9"
	Water9Surf2
		icon_state="9N"
		
